DevFelio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("common.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + debug_toolbar_urls()

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/urls.py
from django.urls import path

from common import views

app_name = "common"


urlpatterns = [
        path("", views.HomeView.as_view(), name="home"),
        path("blogs/", views.BlogListView.as_view(), name="blog"),
        path("blogs/<str:slug>/", views.BlogDetailView.as_view(), name="blog-single"),
        path("add_comment/<int:blog_id>/", views.AddComment.as_view(), name="blog-comment"),
        path("contact/", views.ContactView.as_view(), name="contact"),
        ]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>DevFolio Bootstrap Template</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Bootstrap CSS File -->
  <link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Libraries CSS Files -->
  <link href="{% static 'lib/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'lib/ionicons/css/ionicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'lib/lightbox/css/lightbox.min.css' %}" rel="stylesheet">
  
  <!-- Main Stylesheet File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
    Theme Name: DevFolio
    Theme URL: https://bootstrapmade.com/devfolio-bootstrap-portfolio-html-template/
    Author: BootstrapMade.com
    License: https://bootstrapmade.com/license/
  ======================================================= -->
</head>

<body id="page-top">

  <!--/ Nav Star /-->
  <nav class="navbar navbar-b navbar-trans navbar-expand-md fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll" href="#page-top">DevFolio</a>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarDefault"
        aria-controls="navbarDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span></span>
        <span></span>
        <span></span>
      </button>
      <div class="navbar-collapse collapse justify-content-end" id="navbarDefault">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link js-scroll active" href="{% url 'common:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll" href="#about">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll" href="#service">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll" href="#work">Work</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll" href="#blog">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll" href="#contact">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!--/ Nav End /-->

  
  {% block content %}
  {% endblock %}

  <!--/ Section Contact-Footer Star /-->

  <!--/ Section Contact-footer End /-->

  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
  <div id="preloader"></div>

  <!-- JavaScript Libraries -->
  <script src="{% static 'lib/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'lib/jquery/jquery-migrate.min.js' %}"></script>
  <script src="{% static 'lib/popper/popper.min.js' %}"></script>
  <script src="{% static 'lib/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'lib/easing/easing.min.js' %}"></script>
  <script src="{% static 'lib/counterup/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'lib/counterup/jquery.counterup.js' %}"></script>
  <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'lib/lightbox/js/lightbox.min.js' %}"></script>
  <script src="{% static 'lib/typed/typed.min.js' %}"></script>
  <!-- Contact Form JavaScript File -->
  <script src="{% static 'contactform/contactform.js' %}"></script>

  <!-- Template Main Javascript File -->
  <script src="{% static 'js/main.js' %}"></script>

</body>
</html>

templates/blog-single.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  <!--/ Intro Skew Star /-->
  <div class="intro intro-single route bg-image" style="background-image: url(/static/img/overlay-bg.jpg)">
    <div class="overlay-mf"></div>
    <div class="intro-content display-table">
      <div class="table-cell">
        <div class="container">
          <h2 class="intro-title mb-4">Blog Details</h2>
          <ol class="breadcrumb d-flex justify-content-center">
            <li class="breadcrumb-item">
              <a href="{% url 'common:home' %}">Home</a>
            </li>
            <li class="breadcrumb-item">
              <a href="/blogs/">Library</a>
            </li>
            <li class="breadcrumb-item active">Data</li>
          </ol>
        </div>
      </div>
    </div>
  </div>
  <!--/ Intro Skew End /-->

  <!--/ Section Blog-Single Star /-->
  <section class="blog-wrapper sect-pt4" id="blog">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <div class="post-box">
            <div class="post-thumb">
              <img src="{{ object.large_image.url }}" class="img-fluid" alt="">
            </div>
            <div class="post-meta">
              <h1 class="article-title">{{ object.title }}</h1>
              <ul>
                <li>
                  <span class="ion-ios-person"></span>
                  <a href="{% url 'common:blog-single' object.slug %}">{{ object.author }}</a>
                </li>
                <li>
                  <span class="ion-pricetag"></span>
                  {% for category in object.categories.all %}
                  <a href="{% url 'common:blog-single' object.slug %}">{{ category.title }}</a>
                  {% endfor %}
                </li>
                <li>
                  <span class="ion-chatbox"></span>
                  <a href="{% url 'common:blog-single' object.slug %}">{{object.read_time}}</a>
                </li>
              </ul>
            </div>
            <div class="article-content">
              <p>
                {{ object.content|safe }}
              </p>
            </div>
          </div>
          <div class="box-comments">
            <div class="title-box-2">
              <h4 class="title-comments title-left">Comments (34)</h4>
            </div>
            <ul class="list-comments">
              {% for comment in comments %}
              <li>
                <div class="comment-avatar">
                  <img src="/static/img/testimonial-2.jpg" alt="">
                </div>
                <div class="comment-details">
                  <h4 class="comment-author">{{ comment.name }}</h4>
                  <span>{{ comment.published_date }}</span>
                  <p>
                    {{ comment.comment }}
                  </p>
                  <a href="3">Reply</a>
                </div>
              </li>
              {% endfor %}
            </ul>
          </div>
          <div class="form-comments">
            <div class="title-box-2">
              <h3 class="title-left">
                Leave a Reply
              </h3>
            </div>
            <form class="form-mf" method="post" action="{% url 'common:blog-comment' object.id %}">
              {% csrf_token %}
              <div class="row">
                <div class="col-md-6 mb-3">
                  <div class="form-group">
                    <input type="text" class="form-control input-mf" id="inputName" placeholder="Name *" name="name" required>
                  </div>
                </div>
                <div class="col-md-6 mb-3">
                  <div class="form-group">
                    <input type="email" class="form-control input-mf" id="inputEmail1" placeholder="Email *" name="email" required>
                  </div>
                </div>
                <div class="col-md-12 mb-3">
                  <div class="form-group">
                    <input type="subject" class="form-control input-mf" id="inputUrl" placeholder="Website" name="subject">
                  </div>
                </div>
                <div class="col-md-12 mb-3">
                  <div class="form-group">
                    <textarea id="textMessage" class="form-control input-mf" placeholder="Comment *" name="comment"
                      cols="45" rows="8" required></textarea>
                  </div>
                </div>
                <div class="col-md-12">
                  <button type="submit" class="button button-a button-big button-rouded">Send Message</button>
                </div>
              </div>
            </form>
          </div>
        </div>
        <div class="col-md-4">
          <div class="widget-sidebar sidebar-search">
            <h5 class="sidebar-title">Search</h5>
            <div class="sidebar-content">
              <form>
                <div class="input-group">
                  <input type="text" class="form-control" placeholder="Search for..." aria-label="Search for...">
                  <span class="input-group-btn">
                    <button class="btn btn-secondary btn-search" type="button">
                      <span class="ion-android-search"></span>
                    </button>
                  </span>
                </div>
              </form>
            </div>
          </div>
          <div class="widget-sidebar">
            <h5 class="sidebar-title">Recent Post</h5>
            <div class="sidebar-content">
              <ul class="list-sidebar">
                <li>
                  <a href="#">Atque placeat maiores.</a>
                </li>
                <li>
                  <a href="#">Lorem ipsum dolor sit amet consectetur</a>
                </li>
                <li>
                  <a href="#">Nam quo autem exercitationem.</a>
                </li>
                <li>
                  <a href="#">Atque placeat maiores nam quo autem</a>
                </li>
                <li>
                  <a href="#">Nam quo autem exercitationem.</a>
                </li>
              </ul>
            </div>
          </div>
          <div class="widget-sidebar">
            <h5 class="sidebar-title">Archives</h5>
            <div class="sidebar-content">
              <ul class="list-sidebar">
                <li>
                  <a href="{% url 'common:blog-single' object.slug %}">{{ object.published_date }}</a>
                </li>
                <li>
                  <a href="#">April, 2017.</a>
                </li>
                <li>
                  <a href="#">Nam quo autem exercitationem.</a>
                </li>
                <li>
                  <a href="#">Atque placeat maiores nam quo autem</a>
                </li>
                <li>
                  <a href="#">Nam quo autem exercitationem.</a>
                </li>
              </ul>
            </div>
          </div>
          <div class="widget-sidebar widget-tags">
            <h5 class="sidebar-title">Tags</h5>
            <div class="sidebar-content">
              {% for tag in object.tags.all %}
              <ul>
                <li>
                  <a href="{% url 'common:blog-single' object.slug %}">{{ tag.title }}</a>
              </ul>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--/ Section Blog-Single End /-->

{% endblock %}

templates/blog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!--/ Intro Skew Star /-->
<div class="intro intro-single route bg-image" style="background-image: url(/static/img/overlay-bg.jpg)">
    <div class="overlay-mf"></div>
    <div class="intro-content display-table">
      <div class="table-cell">
        <div class="container">
          <h2 class="intro-title mb-4">Blog Details</h2>
          <ol class="breadcrumb d-flex justify-content-center">
            <li class="breadcrumb-item">
              <a href="{% url 'common:home' %}">Home</a>
            </li>
            <li class="breadcrumb-item active">
              <a href="/blogs/">Library</a>
            </li>
          </ol>
        </div>
      </div>
    </div>
  </div>
  <!--/ Intro Skew End /-->


<section id="blog" class="blog-mf sect-pt4 route">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="title-box text-center">
            <h3 class="title-a">
              Blog
            </h3>
            <p class="subtitle-a">
              Lorem ipsum, dolor sit amet consectetur adipisicing elit.
            </p>
            <div class="line-mf"></div>
          </div>
        </div>
      </div>
      <div class="row">
        {% for blog in objects %}
        <div class="col-md-4">
          <div class="card card-blog">
            <div class="card-img">
              <a href="{% url 'common:blog-single' blog.slug %}"><img src="{{ blog.main_image.url }}" alt="" class="img-fluid"></a>
            </div>
            <div class="card-body">
              <div class="card-category-box">
                <div class="card-category">
                  {% for category in blog.categories.all %}
                  <h6 class="category">{{ category.title }}</h6>
                  {% endfor %}
                </div>
              </div>
              <h3 class="card-title"><a href="{% url 'common:blog-single' blog.slug %}">{{ blog.title }}</a></h3>
              <p class="card-description">
                {{ blog.description }}
              </p>
            </div>
            <div class="card-footer">
              <div class="post-author">
                <a href="{% url 'common:blog-single' blog.slug %}">
                  <img src="/static/img/testimonial-2.jpg" alt="" class="avatar rounded-circle">
                  <span class="author">{{ blog.author }}</span>
                </a>
              </div>
              <div class="post-date">
                <span class="ion-ios-clock-outline"></span> {{ blog.read_time }}
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>

        <div class="bizagne--pagination">
            {% if page_obj.has_previous %}
            <a href="?page={{page_obj.previous_page_number}}"><i class="fa fa-angle-left"></i></a>
            {% endif %}

            {% for page in page_obj.paginator.page_range %}
            {% if page_obj.number == range %}
            <span class="current" style="color:red;">{{page}}</span>
            {% else %}
            <a href="?page={{page}}">{{page}}</a>
            {% endif %}
            {% endfor %}
        
            {% if page_obj.has_next %}
            <a href="?page={{page_obj.next_page_number}}"><i class="fa fa-angle-right" ></i></a>
        </div>
        {% endif %}
    <!-- End of Pagination -->
        
        
    </div>
  </section>      

{% endblock %}